name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    
    container:
      image: erlang:23.0
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit tests
      run: rebar3 as test eunit
    - name: Run CT tests
      run: rebar3 as test ct --spec ./test/spec.spec --sname tests --readable true --basic_html false
